### ISSUE TITLE
"arm" vs "arm64"

### ISSUE THREAD

**Issue by vielmetti** [CircleCI-Public/arm-preview-docs#1]
The only thing I can think about regarding naming in this system is that Arm is the company, but they design chips with several different instruction sets, and it's a meaningful difference. "arm64" (or less commonly "aarch64") is the 64-bit  ARMv8 instruction set found in modern server processors, and the text should reflect any understanding that it's primarily 64-bit support (or if you do provide 32-bit support like for "armhf" or "armel" found on Raspberry Pi's) that's clear.

cc @appplemac @worksonarm

**Comment by appplemac** [comment]
Thanks @vielmetti ! We’ll update the docs + other places to clarify.

**Comment by appplemac** [comment]
Apologies for taking so long to update this. Updated the README to clarify that only `arm64` is supported for now. Thanks again!
