### ISSUE TITLE
Larger arm64 executors, please

### ISSUE THREAD

**Issue by jwm** [CircleCI-Public/arm-preview-docs#2]
Hi, I took a look at the ARM preview today.

Unfortunately, the existing ARM executor sizes are too small for us. Our Golang-based backend is fairly large, and we use use `2xlarge` executors.

Will there be larger executors available further into the preview?

**Comment by appplemac** [comment]
Hi @jwm, thanks for your interest in larger machines! I’ll relay to the team to see if we can add larger options.

**Comment by sebastian-lerner** [comment]
Hi @jwm, this is now live: https://circleci.com/product/features/resource-classes/
